name: Spec

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        crystal: [1.1.0, 1.0.0]

    container:
      image: crystallang/crystal:${{ matrix.crystal }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
    - name: Install dependencies and build codegen
      run: shards build
    - name: Run crystal spec
      run: make spec
